export type Status = "queued" | "running" | "completed" | "partial" | "failed" | "cancelled" | "skipped";
export interface ResearchRequest { market?: "CN" | "US"; symbol: string; question: string; mode: "demo" | "live"; as_of: string; lookback_days: number; use_llm: boolean }
export interface Config { alpha_vantage_ready: boolean; live_ready: boolean; llm_ready: boolean; demo_symbols: string[]; version: string }
export interface Evidence { id: string; title: string; source: string; url: string | null; observed_at: string; retrieved_at: string; kind: string; is_demo: boolean; snapshot_hash: string; note: string }
export interface Bar { date: string; close: number; volume: number }
export interface Claim { text: string; kind: string; evidence_ids: string[] }
export interface News { category?: "news" | "announcement"; time_precision?: string; title: string; summary: string; published_at: string; source: string; url: string | null; evidence_id: string }
export interface Metrics { last_close: number; last_date: string; daily_change_pct: number; period_return_pct: number; sma20: number | null; sma50: number | null; rsi14: number | null; volatility_pct: number | null; max_drawdown_pct: number; trend: string; sample_size: number; methodology: string }
export interface Report { market?: "CN" | "US"; currency?: string; adjustment?: string; name?: string; provider?: string; title: string; symbol: string; question: string; as_of: string; mode: string; generated_at: string; summary: string; status: Status; metrics: Metrics; claims: Claim[]; evidence: Evidence[]; risks: {level: string; title: string; detail: string}[]; conflicts: string[]; limitations: string[]; news: News[]; chart: Bar[]; macro: { summary: string; interpretation?: string }; ai_synthesis: { summary: string; claims: Claim[]; uncertainties: string[] } | null; engine: string; usage: { input_tokens: number; output_tokens: number; estimated_cost_usd: number | null } | null; planner?: string; plan?: Plan | null; agent_findings?: Record<string, AgentFinding>; revisions?: Record<string, unknown>; challenges?: ChallengeRecord[]; arbitration?: Arbitration | null }
export interface Task { id: string; request: ResearchRequest; status: Status; created_at: string; finished_at: string | null; error: string | null }
export interface Detail extends Task { attempts: number; agents: { name: string; status: Status; duration_ms: number | null; error: string | null; output: {summary?: string; reason?: string} | null }[]; events: {id: number; kind: string; created_at: string; message: string}[]; report: Report | null }
export interface Plan { enabled_agents: string[]; rationale: string; focus: Record<string, string>; skipped_reason: Record<string, string> }
export interface AgentFinding { headline: string; findings: Claim[]; confidence: string; open_questions: string[] }
export interface ChallengeRecord { target_agent: string; reason: string; request: string; round: number; accepted: boolean; resolved: boolean }
export interface Arbitration { status?: Status; conflict: string; ruling: string; rationale: string; evidence_ids: string[]; summary?: string; reason?: string }
